spring.application.name=board_250618
server.port=8989

# maria db
#spring.datasource.url=jdbc:mariadb://localhost:3306/sola
spring.datasource.url=jdbc:mariadb://svc.sel5.cloudtype.app:30615/sola
spring.datasource.username=bpk
spring.datasource.password=1234
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
#spring.jpa.hibernate.ddl-auto=create-drop
