name: Deploy to Cloudtype

on:
  push:
    branches:
      - main  # main 브랜치에 푸시될 때마다 실행

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy to Cloudtype
        uses: cloudtype-github-actions/deploy@v1
        with:
          api_token: ${{ secrets.CLOUDTYPE_API_TOKEN }}
          project: your-cloudtype-id/project-name
          service: service-name
